openapi: 3.1.0
info:
  title: RealWorld in Ktor
  description: Implementation of https://github.com/gothinkster/realworld
  version: 1.0.0
externalDocs:
  url: /
servers:
  - url: http://localhost:8080
    description: Local API
tags: []
paths:
  /api/users:
    post:
      tags:
        - user
      description: Register user
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.example.routes.UserRequest"
        required: false
      responses:
        "200":
          description: Success
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.example.routes.UserResponse"
        "400":
          description: An invalid request
          headers: {}
      deprecated: false
  /api/user:
    get:
      tags:
        - user
      description: Get current user
      parameters: []
      responses:
        "200":
          description: Current user
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.example.routes.UserResponse"
      deprecated: false
components:
  schemas:
    com.example.routes.UserRequest:
      type: object
      properties:
        email:
          type: string
          title: String
        password:
          type: string
          title: String
        username:
          type: string
          title: String
      required:
        - email
        - password
        - username
      title: UserRequest
    com.example.routes.UserResponse:
      type: object
      properties:
        bio:
          type: string
          title: String
        email:
          type: string
          title: String
        image:
          type: string
          title: String
        token:
          type: string
          title: String
        username:
          type: string
          title: String
      required:
        - bio
        - email
        - image
        - token
        - username
      title: UserResponse
  examples: {}
webhooks: {}