openapi: "3.1.0"
info:
  title: "realword ktor API"
  description: "realword ktor API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /whatsup:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "What's up motherfuckers?"